### PR TITLE
[IMP] mail: remove props alias

### PR DESCRIPTION
**Pull request by phenix-factory**

### CODE REVIEW

**Comment by alexkuhn** [comment]
Tests do not pass, due to template still looking for `this.message`.
Should either adapt template too to use `props.message` instead, or define a getter `message` to keep most of code unchanged.

**Review by alexkuhn — CHANGES_REQUESTED** [review]
Tests do not pass, due to template still looking for `this.message`.
Should either adapt template too to use `props.message` instead, or define a getter `message` to keep most of code unchanged.

**Comment by phenix-factory** [comment]
@alexkuhn My bad, I forgot the template...
I have updated and rebased this PR

**Review by seb-odoo — COMMENTED** [review]
I feel like this is too much diff and noise, I'd rather just have a getter as Alex suggested.

**Comment by phenix-factory** [comment]
> I feel like this is too much diff and noise, I'd rather just have a getter as Alex suggested.

Ok, I made an other PR for this.
https://github.com/odoo-dev/odoo/pull/1533

**Pull request closed without merging**
