### PR TITLE
[IMP] onboarding, *: customize step image

### PR DESCRIPTION
**Pull request by flch-odoo**
= account, sale

This commit allows users to modify the panel image for the
onboarding steps. This is especially necessary for additional
onboardings that can be/could have been created, or if the
appointment onboarding was modified, as it was chosen to not
overly complicate the upgrade and simply not modify these records.

We also customize the placeholder icon to be one of these icons
instead of the default "camera" image.

Finally, a few icons are renamed to be more generally usable.

See odoo-dev/enterprise#573

(Follow-up of #2460)

### CODE REVIEW

**Comment by flch-odoo** [comment]
Hello @stefanorigano , @xlu-odoo, this PR (and related ENT) is ready for you to review.

cc @tde-banana-odoo

**Comment by flch-odoo** [comment]
Hello @aab-odoo , could you review and/or merge this please?

edit: It's necessary to have a usable UX especially with the choices we had to make for the upgrade.

**Review by aab-odoo — COMMENTED** [review]
@flch-odoo Why me? Also this PR needs a rebase

**Comment by stefanorigano** [comment]
Hello @aab-odoo , my bad, I suggested @flch-odoo to get in touch with you 'cause I thought that this was needed for milk's merge :)

**Comment by flch-odoo** [comment]
Re-targeting to odoo/odoo.

**Pull request closed without merging**
