### PR TITLE
[FIX] mail: wrong text description for call

### PR DESCRIPTION
**Pull request by zel-odoo**

### CODE REVIEW

**Review by alexkuhn — CHANGES_REQUESTED** [review]
The changes does not make it `l10n` compliant.
Actually all other showing of notifications in a thread are wrong: they should not concatenate author name and body in order to form a sentence.

**Comment by zel-odoo** [comment]
Yes,  some phrases like "Guest has joined channel" should be changed accordingly as you said. Do you think it is good to format everything into the body and not use the author's name for the notifications?

**Comment by alexkuhn** [comment]
Yes, I made a task + PR for such changes some time ago:
https://www.odoo.com/web#id=2973689&cids=1&menu_id=4720&action=333&active_id=5779&model=project.task&view_type=form

The problem is that old messages will break without migration scripts, and migration scripts are costly. This is the kind of error that is quite costly to fix

**Comment by seb-odoo** [comment]
Do we still need this PR?

**Comment by alexkuhn** [comment]
Let's just drop the PR. If we need it at some point, let's just redo it from scratch

**Pull request closed without merging**
