### PR TITLE
[REF] web: extract company service from user service

### PR DESCRIPTION
**Pull request by ged-odoo**
https://github.com/odoo-dev/enterprise/pull/148

### CODE REVIEW

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robdoo rebase-ff r+

**Comment by aab-odoo** [comment]
robodoo rebase-ff r+

**Comment by aab-odoo** [comment]
robodoo retry

**Pull request closed without merging**
