### PR TITLE
[FIX] bus: restart poll just after abort

### PR DESCRIPTION
**Pull request by seb-odoo**

### CODE REVIEW

**Comment by seb-odoo** [comment]
For our branch... Should be backported (? 12.3)

**Review by alexkuhn — APPROVED** [review]
yes, should be fixed in 12.3

**Comment by seb-odoo** [comment]
Fixed in 12.3, let's merge here too so I can work on livestream without having to wait for forward-port and rebase of our main branch.

**Comment by seb-odoo** [comment]
https://github.com/odoo/odoo/pull/49340

**Pull request merged**
