### PR TITLE
[REF] mail: add service to service registry in their file

### PR DESCRIPTION
**Pull request by alexkuhn**

### CODE REVIEW

**Comment by seb-odoo** [comment]
As expected, this is breaking runbot due to issue in assets bundle. These have to be resolved first (in master).

**Comment by alexkuhn** [comment]
@seb-odoo runbot's green, the crash in runbot was due to typo and still need of registering services in `webclient_setup` (because our `start()` method relies on legacy MockServer)

**Comment by seb-odoo** [comment]
still red for me

**Comment by alexkuhn** [comment]
it was red due to rtc session bug, should be green

**Review by seb-odoo — APPROVED** [review]

**Pull request merged**
