### PR TITLE
[IMP] web: improve registry.get api with default value

### PR DESCRIPTION
**Pull request by ged-odoo**

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+ :love_you_gesture:

**Comment by ged-odoo** [comment]
robodoo r+

**Comment by sdegueldre** [comment]
@robodoo r+

**Comment by aab-odoo** [comment]
> I'm sorry, @aab-odoo. I'm afraid I can't do that.

:middle_finger:

**Comment by aab-odoo** [comment]
robodoo r+ please :love_you_gesture: :love_you_gesture: :love_you_gesture:

**Comment by ged-odoo** [comment]
robodoo retry

**Pull request closed without merging**
