### PR TITLE
[IMP] web: `controlPanel`, adapt for dark mode

### PR DESCRIPTION
**Pull request by xlu-odoo**
task-2710677

### CODE REVIEW

**Comment by xlu-odoo** [comment]
@stefanorigano 👋

**Comment by stefanorigano** [comment]
Unfortunately not the expected result, header's buttons shouldn't have a bg color.
image

The ideal result should be what we already get for the mobile chatter. Could you propose a similar implementation?
image

**Comment by xlu-odoo** [comment]
Updated (with: https://github.com/odoo-dev/enterprise/pull/377)

image

Did you see it that way @stefanorigano ?

**Comment by stefanorigano** [comment]
visually it's ok... but I'm against using default BS classes (`btn-link`) and than override them, it's never a good idea ;)

I propose to create a common set of variables handling header's bg and action text colors.
The variables should be shared between `mail` chatWindows, `voip` and these mobile windows.... what do you think?

**Comment by xlu-odoo** [comment]
👋 @stefanorigano (also: https://github.com/odoo-dev/enterprise/pull/377/commits )

**Pull request closed without merging**
