### PR TITLE
[MERGE] PWA support

### PR DESCRIPTION
**Pull request by tde-banana-odoo**

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Hello @pparidans ! Glad to see it coming :) .

I think you should rebase as it seems you are based on an old branch :) . Easiest is to do a rebase -i and keep only your pwa commit (otherwise you will enter a rebase hell).

Thanks !

**Comment by pparidans** [comment]
@tde-banana-odoo Wasn't sure if you preferred to merge it into your main PR or as a follow-up of your work ;)

Will rebase and finish the work here.

**Comment by tde-banana-odoo** [comment]
Well if we can include it in the main PR and merge everything once, I think it is better. Our target is for Friday (hem); if it does not seem doable for you we can do a post-merge-merge if necessary :) .

**Comment by tde-banana-odoo** [comment]
Cherry-picked in https://github.com/odoo/odoo/pull/53540 !

**Pull request closed without merging**
