### PR TITLE
[FIX] mail : activity mark done buttons spacing with feedback textarea

### PR DESCRIPTION
**Pull request by xdu-odoo**
Task 2243504

### CODE REVIEW

**Comment by seb-odoo** [comment]
Do you know exactly why that issue was only on Firefox? What value was set on Chrome automatically?

**Comment by xdu-odoo** [comment]
> Do you know exactly why that issue was only on Firefox? What value was set on Chrome automatically?

There is a padding from bootstrap on the textarea which seems to be ignored by Firefox I don't know exactly why. Other strange thing is that on chrome the padding and the margin are kind of "merged". So if the padding is 5px and the margin is 7px, then the space will be of 7px.

**Comment by seb-odoo** [comment]
Padding should obviously not create a margin so the behavior of Firefox is normal. It's just so that the text inside the area is not too close to the border internally.

The bug also seems to be related to `.form-control` computing a complicated `height` that is overridden by `height: auto` in `textarea.form-control`.

Since all of those are in bootstrap I guess just adding a margin where we actually want one as is done in this PR is an obvious choice, so we can merge it.

**Review by seb-odoo — APPROVED** [review]

**Comment by seb-odoo** [comment]
So just add task in commit message and merge.

**Comment by seb-odoo** [comment]
task- not # because it looks like a PR number otherwise

But it's fine this time, we're going to squash this at some point.

**Comment by xdu-odoo** [comment]
Okay will remember that

**Pull request merged**
