### PR TITLE
[REF] base_address_extended: Added city_id and city fields in res.partner model because they are needed in some localisations like Mexico

### PR DESCRIPTION
**Pull request by hugho-ad**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@qdp-odoo coul you merge this change? `city_id` and `city` fields was ommited in your changes

Regards

**Comment by nhomar** [comment]
@hugho-ad They are preparing an special behavior for such fields.

I will merge to vauxoo/odoo in order to move forward vx/mx

**Comment by nhomar** [comment]
@qdp-odoo Am I right this fields will not be necesary to be added?

**Comment by moylop260** [comment]
Should we add these fields to `res.partner` from our modules or I'm missing something?

**Pull request closed without merging**
