### PR TITLE
[REF] slightly improve file upload api

### PR DESCRIPTION
**Pull request by ged-odoo**

### CODE REVIEW

**Comment by tsm-odoo** [comment]
@ged-odoo Can I update this PR in order for it to be merged ? Looks like it is a bit abandonned :)

**Comment by ged-odoo** [comment]
@tsm-odoo sure, go for it!

**Comment by seb-odoo** [comment]
Do we still need this PR?

**Comment by ged-odoo** [comment]
not really important, easier to close it

**Pull request closed without merging**
