### PR TITLE
[REF] web: update systray registry to take Component/props

### PR DESCRIPTION
**Pull request by ged-odoo**

### CODE REVIEW

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by ged-odoo** [comment]
robodoo r+ @aab-odoo I just fixed the conflict. note that the large diff in navbar is caused by someone (not me) not using the tooling...

**Comment by aab-odoo** [comment]
robodoo r+

**Comment by aab-odoo** [comment]
robodoo r+

**Pull request closed without merging**
