### PR TITLE
[FIX] mail: avoid attachment button flicker

### PR DESCRIPTION
**Pull request by phenix-factory**

### CODE REVIEW

**Comment by seb-odoo** [comment]
Looks wrong to remove the save of new record on click?

**Comment by phenix-factory** [comment]
It's working all the same without this, and I can't understand why we have this event

**Comment by seb-odoo** [comment]
Did you test on draft records too?

**Comment by seb-odoo** [comment]
need rebase

**Comment by phenix-factory** [comment]
> Did you test on draft records too?

I didn't, but that look like the use case I didn't think about.

**Pull request merged**
