### PR TITLE
[FIX] web: bind to hashchange at the end of the initial loading

### PR DESCRIPTION
**Pull request by kebeclibre**
When the web client is completely ready, it triggers an event "web_client_ready" on the bus
Some Mail OWL components rely on that mechanism to be mounted
i.e. DialogManager and ChatWindowManager

When eveluating the action to display at startup, the webclient mechanism
implies that we push the location hash each time a relevant data is availaible
e.g. menu_id etc...

Now, before this commit, since the hashchange handler was bound before that evaluation
it was actually triggered each time the JQuery bbq pushed a url state (this is in the API)
doc: http://benalman.com/code/projects/jquery-bbq/docs/files/jquery-ba-bbq-js.html#jQuery.bbq.pushState

This undercutted the initial loading promise chain to finish and the event "web_client_ready" was never triggered
preventing everything that relied on it to be mounted

The DialogManager and ChatWindowManager were never available

After this commit, we bind the hashchange handler after the whole loading has finished
hence ensuring the loading to finish and return

It is worth noting that the hashchange mechanism is largely outdated and will change
in a more reliable way in the near future with the conversion of the webClient to OWL
the drop of JQuery BBQ and the direct reliance on window.history.pushState
doc: https://developer.mozilla.org/en-US/docs/Web/API/History/pushState#:~:text=The%20state%20object%20is%20a,the%20history%20entry's%20state%20object.
and on the window's "popstate" event
doc: https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event

This commit mus be applied on the enterprise webclient too

### CODE REVIEW

**Comment by kebeclibre** [comment]
@aab-odoo 
A quick check on this for the mail-owl branch.
I know that this fix should probably be done early than master, but since no one complained..... and that It will change with the refactor of webclient anyway....

**Comment by kebeclibre** [comment]
enterprise branch (exactly same fix) https://github.com/odoo-dev/enterprise/tree/master-mail-owl-lpe

**Comment by seb-odoo** [comment]
I don't think I'm the right person to review this, but we'll need this fix for our branch (so in theory next week...).

**Review by aab-odoo — APPROVED** [review]
I approve the hashchange commit

**Comment by seb-odoo** [comment]
Thank you for checking it.

@kebeclibre could you please create a PR with that commit in master and merge it? We should get this one through a rebase master.

**Comment by seb-odoo** [comment]
I suppose you can delete this one.

**Pull request closed without merging**
