### PR TITLE
[IMP] mail: composer suggestions

### PR DESCRIPTION
**Pull request by zel-odoo**

### CODE REVIEW

**Comment by alexkuhn** [comment]
👆rebased to recent changes (notably new channel member model).
Also fixing very few issues in PR to make it work like it was before rebase, and made most tests pass.

Note that ChannelMember =/= Partner. The code was slightly adapted to take that into account.

2 tests do not pass:
- 1 of them I haven't checked why render doesn't start;
- the 2nd is "Stop edition on press escape", and the feature is not working as expected after the changes in this PR: we need 2 escapes to stop editing, instead of a single escape.

**Comment by alexkuhn** [comment]
PR is quite long, and there are many things to be improved on this PR.

The most important is to ensure everything works good, notably all tests must pass. After that, will do some code cleaning a bit everywhere to reduce the complexity of this feature significantly.

**Comment by zel-odoo** [comment]
> 👆rebased to recent changes (notably new channel member model). Also fixing very few issues in PR to make it work like it was before rebase, and made most tests pass.
> 
> Note that ChannelMember =/= Partner. The code was slightly adapted to take that into account.
> 
> 2 tests do not pass:
> 
> * 1 of them I haven't checked why render doesn't start;
> * the 2nd is "Stop edition on press escape", and the feature is not working as expected after the changes in this PR: we need 2 escapes to stop editing, instead of a single escape.

Test passed and now time for cleaning up :)

**Review by alexkuhn — COMMENTED** [review]
👆rebased

Functionally looks alright.
Small bug when navigating up/down:

navigation-outside

Fine to merge as-is.
Just waiting for other readily available PR that adds smaller feature that are required for this one.
So might be worth waiting a bit to merge this one, after the smaller PR.

**Comment by zel-odoo** [comment]
> 

I think what the gif showing is designed on purpose. When you navigate using the arrow down/up, there will be a null state after you reach the end. we can disable this if don't want but this is the default logic for all autocomplete components in odoo. So, I allow this to make the logic consistent within odoo. If we want to disable that I can update the code and remove this feature.

**Comment by alexkuhn** [comment]
The problem with this `null` state is that it's too likely to make mistake and post a message with just `@` at the end.
That's because ENTER in this null state is not handled in autocomplete, and it's being immediately turned into a quick message post in discuss app/chat window.

This feature can make some sense in chatter, where ENTER doesn't lead to accidental message post. Discord might have same problem and they don't have this `null` state. Github doesn't have this problem and they have this `null` state.

Considering we have the risk of this accidental ENTER, I would not allow this `null` state in autocomplete. At the very least, not in Discuss app / chat window. Chatter would follow just for consistency.

**Comment by alexkuhn** [comment]
Could you please rebase with recent changes that have been merged?
Notably this PR was merged, and covers some of code changes in this PR:
https://github.com/odoo-dev/odoo/pull/1550
Thanks!

**Review by alexkuhn — CHANGES_REQUESTED** [review]
Tests do not pass, so unfortunately cannot simply merge and do (lots of) follow-up PRs.

Make sure all mail tests pass.

When it's all green and working, I'll put all priority on this PR to understand it and prepare work for follow-up PRs, so that we can merge it ASAP.

**Review by alexkuhn — APPROVED** [review]
All tests pass, functionally it works.
Will do some follow-up PRs to clean code.

**Pull request merged**
