### PR TITLE
[FIX] mail: fix composer avatarUrl

### PR DESCRIPTION
**Pull request by phenix-factory**

### CODE REVIEW

**Review by seb-odoo — COMMENTED** [review]
This fix is wrong.

Persona avatarUrl hardcoded to wrong value. Also cannot use channel url in the context of persona. The base URL should be the /web/image one, and we need to use channel specific url in code only in context of channel.

**Comment by alexkuhn** [comment]
Implementation of `avatarUrl` in persona model is wrong and should be fixed.
Conceptually the PR is good and simplifies the logic as it should: composer shows the avatar of self. It's not designed to show avatar of any other member.

**Comment by seb-odoo** [comment]
But due to access rights in python in will not work to just use self avatar for guest or portal users.
If the composer is linked to a channel, the avatar of the current user in the context of that channel needs to be used.

**Comment by phenix-factory** [comment]
> Persona avatarUrl hardcoded to wrong value. Also cannot use channel url in the context of persona. The base URL should be the /web/image one, and we need to use channel specific url in code only in context of channel.

It would be best to abstract this complexity inside persona somehow? That way the problem would be fixed and we could always use `persona.avatarUrl` without thinking about the context?

**Pull request merged**
