### PR TITLE
Master l10n in gst return jva

### PR DESCRIPTION
**Pull request by jva-odoo**

### CODE REVIEW

**Comment by SimonGenin** [comment]
@jva-odoo  Sorry wrong manipulation with github api, didn't mean to close your pr

**Comment by jva-odoo** [comment]
> @jva-odoo Sorry wrong manipulation with github api, didn't mean to close your pr

Okay, No problem. I will re-open it :wink:

**Comment by xmo-odoo** [comment]
master-oco-reportalypse has been proposed for merging (odoo/odoo#94125) and this is still open and in conflict, does this PR actually have a purpose? /cc @smetl @oco-odoo

**Comment by jva-odoo** [comment]
@xmo-odoo no this is cherry-picked by @oco-odoo so I close it. from this PR https://github.com/odoo-dev/odoo/pull/1292

**Pull request closed without merging**
