### PR TITLE
[REF] *: apps icons v4 - Part 1

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Requires:
- https://github.com/odoo-dev/enterprise/pull/500

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
@stefanorigano Main icons LGTM 👍 
I'll fixe minor issues, add forgotten icons (secondary) and flags in the next PR.

**Review by stefanorigano — COMMENTED** [review]
@Brieuc-brd , gradients definition use all the same id (e. `id="white_gradient_1"`)
Base64 compartmentalize the rendering by file, but if we use inline-svgs instead I guess that all these gradients will override each other, no?

**Comment by Brieuc-brd** [comment]
I just did a quick test, and yes you are right, when the svgs are inline, the gradient coordinates are broken. Can I fix this in another PR?

**Comment by stefanorigano** [comment]
> Can I fix this in another PR?
@Brieuc-brd  👍

**Pull request merged**
