### PR TITLE
Fix shortcut dialog ui glitch

### PR DESCRIPTION
**Pull request by msh-odoo**

### CODE REVIEW

**Comment by msh-odoo** [comment]
@Polymorphe57 Ping

**Comment by Polymorphe57** [comment]
Hello @msh-odoo. Just a remark,  I have merged a version of the user menu that is not complete just to give already access to the dialog_manager and crash_manager services but I still need to improve thing (tests, CSS mainly). So my user menu PR was by no means a final product as it usually the case. WOWL has to evolve fast and we sometimes do that for the project. In any case, I'll have a look at your code when I finalize the user menu code. Thank you

**Comment by msh-odoo** [comment]
@Polymorphe57 Thanks, well I checked task and I found it is still not in Done state but I thought this are small glitches and can be fixed quickly and may be you can consider in your development branch so I added it here.

**Comment by Polymorphe57** [comment]
@msh-odoo I have used your commit "[FIX] wowl: add space between user image and user name". It has been merged with one of my PRs. The other was not necessary. Thx. I closed this PR.

**Pull request closed without merging**
