### PR TITLE
[REF] *: apps icons v4 - Part 2

### PR DESCRIPTION
**Pull request by Brieuc-brd**
Requires:
- https://github.com/odoo-dev/enterprise/pull/508

### CODE REVIEW

**Comment by Brieuc-brd** [comment]
@stefanorigano 👋

**Comment by Brieuc-brd** [comment]
@stefanorigano 👋 

- Country flags added ✅ 
- Call to svg for Invoicing fixed ✅ 
- Minor issues with svg code fixed ✅

**Comment by Brieuc-brd** [comment]
New flags removed ✅

**Comment by stefanorigano** [comment]
cherry-picked in `master-milk`, thanks

**Pull request closed without merging**
