### PR TITLE
provisional branch for the controller and view of sale orders

### PR DESCRIPTION
**Pull request by hote-odoo**
Provisonal branch migrating sales app js code to owl. This branch is about SO views and related.

### CODE REVIEW

**Comment by hote-odoo** [comment]
@SimonGenin  hello, did you close the branch because form and list are on master now ?

**Comment by SimonGenin** [comment]
@hote-odoo sorry, bad manipulation with github api, didn't mean to close others PR...

**Comment by SimonGenin** [comment]
You can push again or create a new PR

**Comment by hote-odoo** [comment]
@SimonGenin  no problem :) , this PR concerns form and list views and controllers, can I use master now to branch from ? or do I still use master-wowl ?

**Comment by SimonGenin** [comment]
@hote-odoo You can use master

**Comment by hote-odoo** [comment]
Thank you :)

**Pull request closed without merging**
