### PR TITLE
[IMP] mail: introduce displayName for thread

### PR DESCRIPTION
**Pull request by zel-odoo**
editing chat name on discuss working

### CODE REVIEW

**Review by alexkuhn — APPROVED** [review]
Could re-introduce test "sidebar: chat custom name".
Can you please make a follow-up PR for that?
Thanks!

**Comment by alexkuhn** [comment]
👆rebased (resolved conflicts)
Did not reintroduce the test "sidebar: chat custom name" yet

**Comment by zel-odoo** [comment]
> 

will do that!

**Comment by zel-odoo** [comment]
here it is, https://github.com/odoo-dev/odoo/pull/1558. tested locally already

**Comment by zel-odoo** [comment]
I put the follow-up link in the same place with the main task.

**Pull request merged**
